export var All_cards_Og = [
  // Black Spade
  {
    card: "1",
    fortside: "./Img/All_Cards/row-1-column-1.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "2",
    fortside: "./Img/All_Cards/row-1-column-2.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "3",
    fortside: "./Img/All_Cards/row-1-column-3.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "4",
    fortside: "./Img/All_Cards/row-1-column-4.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "5",
    fortside: "./Img/All_Cards/row-1-column-5.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "6",
    fortside: "./Img/All_Cards/row-1-column-6.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "7",
    fortside: "./Img/All_Cards/row-1-column-7.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "8",
    fortside: "./Img/All_Cards/row-1-column-8.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "9",
    fortside: "./Img/All_Cards/row-1-column-9.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "10",
    fortside: "./Img/All_Cards/row-1-column-10.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "J",
    fortside: "./Img/All_Cards/row-1-column-11.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "Q",
    fortside: "./Img/All_Cards/row-1-column-12.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  {
    card: "K",
    fortside: "./Img/All_Cards/row-1-column-13.png",
    backside: "./Img/All_Cards/backside.png",
    type: "spade",
    colour: "black",
  },
  // Black CLud
  {
    card: "1",
    fortside: "./Img/All_Cards/row-4-column-1.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "2",
    fortside: "./Img/All_Cards/row-4-column-2.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "3",
    fortside: "./Img/All_Cards/row-4-column-3.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "4",
    fortside: "./Img/All_Cards/row-4-column-4.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "5",
    fortside: "./Img/All_Cards/row-4-column-5.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "6",
    fortside: "./Img/All_Cards/row-4-column-6.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "7",
    fortside: "./Img/All_Cards/row-4-column-7.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "8",
    fortside: "./Img/All_Cards/row-4-column-8.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "9",
    fortside: "./Img/All_Cards/row-4-column-9.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "10",
    fortside: "./Img/All_Cards/row-4-column-10.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "J",
    fortside: "./Img/All_Cards/row-4-column-11.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "Q",
    fortside: "./Img/All_Cards/row-4-column-12.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  {
    card: "K",
    fortside: "./Img/All_Cards/row-4-column-13.png",
    backside: "./Img/All_Cards/backside.png",
    type: "club",
    colour: "black",
  },
  // Red Dimonas
  {
    card: "1",
    fortside: "./Img/All_Cards/row-2-column-1.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "2",
    fortside: "./Img/All_Cards/row-2-column-2.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "3",
    fortside: "./Img/All_Cards/row-2-column-3.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "4",
    fortside: "./Img/All_Cards/row-2-column-4.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "5",
    fortside: "./Img/All_Cards/row-2-column-5.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "6",
    fortside: "./Img/All_Cards/row-2-column-6.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "7",
    fortside: "./Img/All_Cards/row-2-column-7.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "8",
    fortside: "./Img/All_Cards/row-2-column-8.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "9",
    fortside: "./Img/All_Cards/row-2-column-9.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "10",
    fortside: "./Img/All_Cards/row-2-column-10.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "J",
    fortside: "./Img/All_Cards/row-2-column-11.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "Q",
    fortside: "./Img/All_Cards/row-2-column-12.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  {
    card: "K",
    fortside: "./Img/All_Cards/row-2-column-13.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Diamond",
    colour: "red",
  },
  // Red Heart
  {
    card: "1",
    fortside: "./Img/All_Cards/row-3-column-1.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "2",
    fortside: "./Img/All_Cards/row-3-column-2.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "3",
    fortside: "./Img/All_Cards/row-3-column-3.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "4",
    fortside: "./Img/All_Cards/row-3-column-4.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "5",
    fortside: "./Img/All_Cards/row-3-column-5.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "6",
    fortside: "./Img/All_Cards/row-3-column-6.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "7",
    fortside: "./Img/All_Cards/row-3-column-7.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "8",
    fortside: "./Img/All_Cards/row-3-column-8.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "9",
    fortside: "./Img/All_Cards/row-3-column-9.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "10",
    fortside: "./Img/All_Cards/row-3-column-10.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "J",
    fortside: "./Img/All_Cards/row-3-column-11.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "Q",
    fortside: "./Img/All_Cards/row-3-column-12.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
  {
    card: "K",
    fortside: "./Img/All_Cards/row-3-column-13.png",
    backside: "./Img/All_Cards/backside.png",
    type: "Heart",
    colour: "red",
  },
];
